config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :blog_posts

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_rich_text :content
  validates :title, presence: true
  validates :content, presence: true

  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current)}

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :new, :create]

  def show
  end

  def index
    @blog_posts = user_signed_in? ? BlogPost.all : BlogPost.published
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to "/blog_posts/#{@blog_post.id}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to "/blog_posts/#{@blog_post.id}"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private
    def blog_post_params
      params.require(:blog_post).permit(:title, :content, :published_at)
    end

    def set_blog_post
      @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div class="flex flex-col">
      <% form.object.errors.full_messages.each do |message| %>
        <h3 class="text-red-500 font-lg"><%= message %></h3>
      <% end %>
    </div>
  <% end %>
  <div class="flex flex-col w-fit">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
    <%= form.button %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= button_to "Delete", @blog_post, method: :delete %>

app/views/blog_posts/index.html.erb
<div class="flex flex-col p-4">
  <%= link_to "New Blog Post", new_blog_post_path, class: "hover:underline, p-2 m-1 bg-gray-200 w-fit" if user_signed_in? %>
  <% @blog_posts.each do |blog_post| %>
    <h2><%= link_to blog_post.title, "/blog_posts/#{blog_post.id}", class: "underline text-yellow-700 text-2xl" %></h2>
    <p><%= blog_post.content %></p>
  <% end %>
</div>

app/views/blog_posts/new.html.erb
<h1 class="text-2xl">New Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<h2 class="text-3xl mb-3"><%= @blog_post.title %></h2>
<p><%= @blog_post.content %></p>
<%= link_to "Edit", "/blog_posts/#{@blog_post.id}/edit" if user_signed_in? %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="flex flex-col">
    <div class="flex flex-row justify-between items-center text-yellow-300 p-2 w-full h-16 bg-red-500">
      <div class="flex flex-col">
        <h1 class="text-3xl">Nice Blog</h1>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <% if user_signed_in? %>
        <div class="flex gap-3 items-center">
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "bg-yellow-300 text-red-500 p-2 rounded-lg hover:bg-yellow-200 transition-colors" %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>